/** Map HR employee / record status labels to shared `Badge` variants. */
export function employeeStatusBadgeVariant(status) {
  const map = {
    Active: 'active',
    Closed: 'gray',
    Approved: 'success',
    Paid: 'success',
    Verified: 'success',
    Generated: 'success',
    Filed: 'success',
    Ready: 'info',
    'Not applicable': 'gray',
    Completed: 'success',
    Resolved: 'success',
    Hired: 'success',
    Open: 'info',
    WFH: 'info',
    'In Progress': 'info',
    Draft: 'gray',
    Review: 'info',
    Locked: 'warning',
    Disbursed: 'success',
    'Missing Structure': 'pending',
    'Missing Bank': 'pending',
    'Ready for payroll': 'success',
    Inactive: 'gray',
    Probation: 'pending',
    Pending: 'pending',
    'Pending Approval': 'pending',
    Notice: 'warning',
    Paused: 'warning',
    Sent: 'warning',
    Rejected: 'danger',
    Exited: 'danger',
    Urgent: 'danger',
    High: 'danger',
    Terminated: 'danger',
    Declined: 'danger',
  }
  return map[status] || 'gray'
}
