'use strict';

const SHIFT_CONFIG = {
  morning: { start: '09:00', end: '18:00', regularHours: 9 },
  evening: { start: '14:00', end: '23:00', regularHours: 9 },
  night: { start: '22:00', end: '07:00', regularHours: 9 },
};

const OT_UID = 'api::overtime-record.overtime-record';

function normalizeWorkShift(value) {
  const raw = String(value || 'morning').toLowerCase();
  return SHIFT_CONFIG[raw] ? raw : 'morning';
}

function parseClockMinutes(value) {
  const match = /^(\d{1,2}):(\d{2})$/.exec(String(value || '').trim());
  if (!match) return null;
  return Number(match[1]) * 60 + Number(match[2]);
}

function getShiftConfig(workShift) {
  return SHIFT_CONFIG[normalizeWorkShift(workShift)] || SHIFT_CONFIG.morning;
}

function calcOvertimeHours(clockOut, workShift = 'morning') {
  const outMin = parseClockMinutes(clockOut);
  const shiftEndMin = parseClockMinutes(getShiftConfig(workShift).end);
  if (outMin == null || shiftEndMin == null) return 0;
  const overtimeMinutes = Math.max(0, outMin - shiftEndMin);
  return Math.round((overtimeMinutes / 60) * 100) / 100;
}

function toMoney(value) {
  return Math.max(0, Math.round(Number(value || 0)));
}

function calcOvertimeAmount(overtimeHours, annualCtc = 0, regularHoursPerDay = 9) {
  const hours = Number(overtimeHours || 0);
  if (!hours || hours <= 0) return 0;
  const annual = toMoney(annualCtc);
  if (!annual) return toMoney(hours * 600);
  const monthlyGross = annual / 12;
  const hourlyRate = monthlyGross / (26 * regularHoursPerDay);
  return toMoney(hours * hourlyRate * 1.5);
}

function shouldTrackOvertime(attendance) {
  const status = String(attendance?.status || '').toLowerCase();
  if (!['present', 'wfh'].includes(status)) return false;
  return Boolean(attendance?.clockIn && attendance?.clockOut);
}

async function syncOvertimeFromAttendance(strapi, { attendance, profile, orgId, actorUserId }) {
  if (!attendance?.id || !attendance?.organizationUser || !attendance?.attendanceDate) return null;

  const orgUserId = Number(
    typeof attendance.organizationUser === 'object'
      ? attendance.organizationUser.id
      : attendance.organizationUser,
  );
  const attendanceDate = attendance.attendanceDate;
  const workShift = normalizeWorkShift(attendance.workShift);
  const shiftConfig = getShiftConfig(workShift);

  const existingRows = await strapi.entityService.findMany(OT_UID, {
    filters: {
      organization: orgId,
      organizationUser: orgUserId,
      recordDate: attendanceDate,
      autoGenerated: true,
    },
    limit: 5,
  });

  const existing = existingRows[0] || null;

  if (!shouldTrackOvertime(attendance)) {
    if (existing && existing.status === 'pending') {
      await strapi.entityService.delete(OT_UID, existing.id);
    }
    return null;
  }

  const overtimeHours = calcOvertimeHours(attendance.clockOut, workShift);
  const annualCtc = toMoney(profile?.annualCtc || profile?.salaryStructure?.ctc || 0);
  const amount = calcOvertimeAmount(overtimeHours, annualCtc, shiftConfig.regularHours);

  if (overtimeHours <= 0) {
    if (existing && existing.status === 'pending') {
      await strapi.entityService.delete(OT_UID, existing.id);
    }
    return null;
  }

  const payload = {
    recordDate: attendanceDate,
    regularHours: shiftConfig.regularHours,
    overtimeHours,
    amount,
    status: existing?.status === 'approved' || existing?.status === 'paid' ? existing.status : 'pending',
    notes: `Auto from attendance (clock out ${attendance.clockOut}, shift ends ${shiftConfig.end})`,
    autoGenerated: true,
    attendanceRecord: attendance.id,
    organizationUser: orgUserId,
    organization: orgId,
    ...(existing ? {} : { createdByUser: actorUserId }),
  };

  if (existing) {
    if (existing.status === 'paid') return existing;
    const entry = await strapi.entityService.update(OT_UID, existing.id, {
      data: {
        regularHours: payload.regularHours,
        overtimeHours: payload.overtimeHours,
        amount: payload.amount,
        notes: payload.notes,
        attendanceRecord: attendance.id,
        ...(existing.status === 'approved' ? {} : { status: 'pending' }),
      },
    });
    return entry;
  }

  return strapi.entityService.create(OT_UID, { data: payload });
}

async function sumApprovedOvertimeForMonth(strapi, orgId, orgUserId, month, year) {
  const monthStr = String(month).padStart(2, '0');
  const lastDay = new Date(year, month, 0).getDate();
  const from = `${year}-${monthStr}-01`;
  const to = `${year}-${monthStr}-${String(lastDay).padStart(2, '0')}`;

  const rows = await strapi.entityService.findMany(OT_UID, {
    filters: {
      organization: orgId,
      organizationUser: orgUserId,
      status: { $in: ['approved', 'paid'] },
      recordDate: { $gte: from, $lte: to },
    },
    limit: 500,
  });

  let overtimeHours = 0;
  let overtimePay = 0;
  for (const row of rows) {
    overtimeHours += Number(row.overtimeHours || 0);
    overtimePay += Number(row.amount || 0);
  }

  return {
    overtimeHours: Math.round(overtimeHours * 100) / 100,
    overtimePay: toMoney(overtimePay),
  };
}

module.exports = {
  SHIFT_CONFIG,
  calcOvertimeHours,
  calcOvertimeAmount,
  shouldTrackOvertime,
  syncOvertimeFromAttendance,
  sumApprovedOvertimeForMonth,
};
